# Generated by Django 4.2.30 on 2026-04-25 11:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='service_type',
            field=models.CharField(db_index=True, help_text='Exemples: wifi, console, product:Film, product:Série', max_length=100),
        ),
    ]
